### ISSUE TITLE
panic after 15 seconds

### ISSUE THREAD

**Issue by davidvanlaatum** [saily/vnc-recorder#10]
when recording selenium tests from selenium/standalone-chrome-debug:latest
it runs fine for 15 seconds then panics with

panic: unsupported encoding EncodingType(458845)00:00:14.06 bitrate=   0.0kbits/s speed=0.927x     

goroutine 1 [running]:
main.recorder(0xc000138000)
        /go/pkg/mod/github.com/saily/vnc-recorder@v0.3.0/main.go:203 +0x1611
github.com/urfave/cli/v2.(*App).RunContext(0xc000136000, {0x6a2c10, 0xc0000b4000}, {0xc0000b2000, 0x5, 0x5})
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:315 +0x8ac
github.com/urfave/cli/v2.(*App).Run(...)
        /go/pkg/mod/github.com/urfave/cli/v2@v2.2.0/app.go:215
main.main()
        /go/pkg/mod/github.com/saily/vnc-recorder@v0.3.0/main.go:77 +0x709

**Comment by silvio201** [comment]
Have you found a solution for this? I currently have the same problem.

**Comment by davidvanlaatum** [comment]
no

**Comment by ternshare** [comment]
It happened to me when vnc-recorder connect to x11vnc server first time. I found modifying the ServerCutText struct could solve the problem: https://github.com/amitbet/vnc2video/issues/9#issuecomment-1216650177
